"""Structured plan data model."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field


@dataclass
class Plan:
    """
    Structured implementation plan generated by the planner.

    Fields mirror the planning output requirements from the product spec.
    """

    summary: str = ""
    assumptions: list[str] = field(default_factory=list)
    steps: list[str] = field(default_factory=list)
    files_to_inspect: list[str] = field(default_factory=list)
    knowledge_to_consult: list[str] = field(default_factory=list)
    commands_to_run: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, indent=2)

    @classmethod
    def from_json(cls, raw: str) -> Plan:
        return cls(**json.loads(raw))

    def is_empty(self) -> bool:
        return not self.summary and not any(
            [
                self.assumptions,
                self.steps,
                self.files_to_inspect,
                self.knowledge_to_consult,
                self.commands_to_run,
                self.risks,
            ]
        )
